default-group: Joueur

redis-sentinel:
   enabled: false
   master: masterName
   auth: authpassword
   sentinels:
      - ip:port
      - ip:port

redis:
   enabled: false
   auth: authpassword
   address: ip
   port: port

sql:
  enabled: false
  host: host
  port: 3306
  database: database
  user: user
  password: password

tab-tags: true
chat-tags: true
chat-format: "{PREFIX}{NAME}{SUFFIX}: {MESSAGE}" # used to format the chat

# Tags are defined through different variables
# To set a variable : /groups setoption <group> <variable> <value> OR /users setoption <user> <variable> <value>
# prefix : before the name
# suffix : after the name (usually used to reset the color)
# Please note : to add a space in a prefix or a suffix, insert "&s"
# Example :
#  - prefix : "[Cool]&s"
#  - suffix empty
#  => "[Cool] zyuiop: hello !"